## VIM CONFIG FILE ##

syntax enable
set number 
set tabstop=2
set softtabstop=2
set showcmd
set cursorline

filetype indent on

set wildmenu
set showmatch
set incsearch
set hlsearch

colorscheme badwolf

if empty(glob('~/.config/vim/autoload/plug.vim'))
    silent !curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs
     \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


# Plugins

call plug#begin('~/.config/vim/plugged')

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }

" Initialize plugin system
call plug#end()

