#! /bin/sh

# Autostart
sxhkd &
feh --bg-scale /home/nik/Pictures/Wallpapers/wall_1.jpg &
picom &
redshift &
nm-applet &
/home/nik/.config/polybar/launch.sh
xset led named "Scroll Lock" &
./.screenlayout/monitor.sh &
xrdb .Xdefaults

# Display config
bspc monitor VGA-1 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           10
bspc config active_border_color "#272727"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false

# Applications rule
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^9'
# bspc rule -a mpv desktop='^5'
bspc rule -a pcmanfm desktop='^4'
bspc rule -a zathura state=tiled
bspc rule -a emacs state=tiled
